Add 'ESMF::ESMF' CMake target alias to support unambiguous linking
esmf-org/esmf pull request #223
Opened 2024-02-03 00:56 UTC by AlexanderRichert-NOAA

This PR adds an alias to the CMake target `ESMF` called `ESMF::ESMF`. This way, when a downstream package calls `target_link_libraries(ESMF::ESMF)` it will fail if the target isn't found, rather than generating a spurious and unwanted `-lESMF` flag. Using the alias leaves the `ESMF` target itself untouched, so no adverse consequences are anticipated.

2024-02-03 00:56 UTC, AlexanderRichert-NOAA commented
@theurich

2024-02-05 16:54 UTC, theurich commented
@danrosen25 Assigning to you to make final decision on pulling into `develop`. It looks good to me.

2024-02-05 16:54 UTC, theurich approved these changes
@AlexanderRichert-NOAA looks good to me. Thanks!

2024-02-05 16:55 UTC, theurich commented
@danrosen25 @oehmke I suggest considering this change also for `patch/8.6.1`.

2024-02-05 17:02 UTC, oehmke commented
Makes sense. Thanks for taking a look. 

> On Feb 5, 2024, at 9:55 AM, Gerhard Theurich ***@***.***> wrote:
> 
> 
> @danrosen25 <https://github.com/danrosen25> @oehmke <https://github.com/oehmke> I suggest considering this change also for patch/8.6.1.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/esmf-org/esmf/pull/223#issuecomment-1927470194>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AE6A7UZT2Y7N6WZ4OH35UELYSEFI7AVCNFSM6AAAAABCXQ63DGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRXGQ3TAMJZGQ>.
> You are receiving this because you were mentioned.
>

2024-02-05 17:29 UTC, danrosen25 commented
@oehmke @theurich 
I'll have to cherry pick 9f0a8be064b1793c9bef5cf16d05dafee7a96dd5 into 8.6.1 but I can do this. Let me run a quick test and make sure we capture all of the cmake modules we provide.

2024-02-05 17:56 UTC, theurich commented
> @oehmke @theurich I'll have to cherry pick [9f0a8be](https://github.com/esmf-org/esmf/commit/9f0a8be064b1793c9bef5cf16d05dafee7a96dd5) into 8.6.1 but I can do this. Let me run a quick test and make sure we capture all of the cmake modules we provide.

It should go into both `develop`, and `patch/8.6.1`. My suggestion would be PR merge into `develop`. Then cherry-pick the hash from `develop` into `patch/8.6.1`.

2024-02-05 18:17 UTC, danrosen25 requested changes
We'd like for you to cherry-pick this commit onto patch/8.6.1 so that we can bring this fix into the 8.6.1 release. As noted in a comment there is a change requested to check for ESMF::ESMF before adding the alias. Also there needs to be a change to the code and two more files.

- src/addon/ESMX/Comps/ESMX_Data/cmake/FindESMF.cmake
- src/addon/ESMX/Driver/cmake/FindESMF.cmake

2024-02-05 18:17 UTC, danrosen25 commented on cmake/FindESMF.cmake
> +  add_library(ESMF::ESMF ALIAS ESMF)
fails if find_package(ESMF) is called multiple times. This is likely in the layered build schemes used to build coupled applications.

Recommended change
```
    if(NOT TARGET ESMF::ESMF)
      add_library(ESMF::ESMF ALIAS ESMF)
    endif()
```

2024-02-05 18:24 UTC, AlexanderRichert-NOAA commented
@danrosen25 sounds good. I've added the `if` and updated the other two files.

2024-02-05 20:13 UTC, AlexanderRichert-NOAA commented
I agree squash-n-merge into develop then cherry pick onto patch branch seems simpler, but I'm happy to do either, just let me know what you guys prefer.

2024-02-05 20:40 UTC, danrosen25 commented
Got it. I'll finish up testing and put it into both branches.

2024-02-05 20:44 UTC, danrosen25 approved these changes

2024-02-05 20:47 UTC, merged

2024-02-05 20:50 UTC, danrosen25 commented
Done!