Update FindESMF.cmake to make ESMF::ESMF main target
esmf-org/esmf pull request #226
Opened 2024-02-13 13:28 UTC by mathomp4

As detailed in #225, our UFS collaborators would like MAPL to provide a `MAPL-targets.cmake` file that uses `ESMF::ESMF` as the target within. From my testing, this can only seem to work if `ESMF::ESMF` is the main target provided by `FindESMF.cmake` and not an `ALIAS`. 

So this PR does that, it essentially makes `ESMF::ESMF` the target the "main" `add_library()` call is run on and then makes `ESMF` the alias.

NOTE: Keeping draft until I can do some testing.

2024-03-12 20:40 UTC, danrosen25 commented
Change requested broke the UFS build
```
ld: cannot find -lesmf
make[5]: *** [sorc/sfc_climo_gen.fd/CMakeFiles/sfc_climo_gen.dir/build.make:101: sorc/sfc_climo_gen.fd/sfc_climo_gen] Error 1
make[4]: *** [CMakeFiles/Makefile2:1401: sorc/sfc_climo_gen.fd/CMakeFiles/sfc_climo_gen.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
```

2024-03-12 22:22 UTC, mathomp4 commented
> Change requested broke the UFS build
> 
> ```
> ld: cannot find -lesmf
> make[5]: *** [sorc/sfc_climo_gen.fd/CMakeFiles/sfc_climo_gen.dir/build.make:101: sorc/sfc_climo_gen.fd/sfc_climo_gen] Error 1
> make[4]: *** [CMakeFiles/Makefile2:1401: sorc/sfc_climo_gen.fd/CMakeFiles/sfc_climo_gen.dir/all] Error 2
> make[4]: *** Waiting for unfinished jobs....
> ```

Well, huh. We might need to ask @AlexanderRichert-NOAA for some advice and help...

2024-03-12 22:28 UTC, danrosen25 commented
I'm testing some more scenarios. Not every FindESMF.cmake file within the ufs-weather-model was consistent. It's possible that I clobbered a FindESMF.cmake file that was customized for a component. I would like to figure this out before making changes to the default library name of ESMF.

2024-03-12 22:34 UTC, mathomp4 commented
> I'm testing some more scenarios. Not every FindESMF.cmake file within the ufs-weather-model was consistent. It's possible that I clobbered a FindESMF.cmake file that was customized for a component. I would like to figure this out before making changes to the default library name of ESMF.

In GEOS one thing I've had to do (locally) is add aliases for `esmf` as well. But that was due to a long-ago choice local to us. Maybe UFS will need to move to `ESMF::ESMF` internally with this change? I am not sure.

I know from spack testing that if you build with spack, it doesn't seem to matter how many other `FindESMF.cmake` files I have around in GEOS, the one from the ESMF install wins!

2024-03-13 15:26 UTC, danrosen25 commented
The issue is related to changing one of these three modules, which are already outdated.
- https://github.com/NOAA-EMC/AQM-utils cmake/FindESMF.cmake
- https://github.com/ufs-community/UFS_UTILS cmake/FindESMF.cmake
- https://github.com/noaa-oar-arl/NEXUS cmake/FindESMF.cmake
My guess is that these modules previously defaulted to the static library and the newer FindESMF module will find any ESMF library unless USE_ESMF_STATIC_LIBS is set.

I was able to build the ufs-weather-model with this newer version of the FindESMF module.

2024-03-13 15:43 UTC, danrosen25 requested changes
Please copy these changes to the following files:
- src/addon/ESMX/Comps/ESMX_Data/cmake/FindESMF.cmake
- src/addon/ESMX/Driver/cmake/FindESMF.cmake

2024-03-13 18:46 UTC, mathomp4 commented
> Please copy these changes to the following files:
> 
> * src/addon/ESMX/Comps/ESMX_Data/cmake/FindESMF.cmake
> * src/addon/ESMX/Driver/cmake/FindESMF.cmake

This should be done.

2024-03-15 22:00 UTC, danrosen25 approved these changes

2024-03-15 22:01 UTC, merged