Install CMake modules into ESMF_INSTALL_CMAKEDIR
esmf-org/esmf pull request #282
Opened 2024-08-29 14:41 UTC by danrosen25

* add hot-to use documentation to FindESMF.cmake
* copy *.cmake files into ESMF_INSTALL_CMAKEDIR (default ESMF_INSTALL_PREFIX/cmake)
* update ESMF user's guide
* add README.md in cmake directory (do not copy into installation as this might override README.md fill in a user's folder)

2024-08-29 19:43 UTC, billsacks approved these changes
Looks great!

2024-08-30 16:14 UTC, theurich requested changes
Looks very good. Just a couple of small suggestions.

2024-08-30 16:14 UTC, theurich commented on src/doc/ESMF_install.tex
> +\item {\tt ESMF\_INSTALL\_CMAKEDIR} -- where to install cmake module files.
None of the other items have a period (.) at the end of sentence. Maybe all should get one? Either way fine with me, just should be consistent.

2024-08-30 16:14 UTC, theurich commented on cmake/README.md
> +used as is or customized for application specific build systems.
Could we add a sentence at the end of this paragraph to point out that CMake module files are typically kept with the project that use them? Maybe:
"Typically CMake module files are copied into the project that use them. They become part of the project and are maintained with it."

2024-08-30 16:24 UTC, theurich commented on src/doc/ESMF_install.tex
> +\item {\tt ESMF\_INSTALL\_CMAKEDIR} -- where to install cmake module files.
I could have sworn that there was no period when I reviewed this... but all I can say is that I definitely need (better) glasses! This looks good as is!

2024-09-04 15:26 UTC, theurich approved these changes
Looks good to me now. Thanks for adding the extra sentences to the usage discussion.

We should discuss during the core call whether this could go into 8.7.0, or should wait for 8.8.0.

2024-09-04 16:30 UTC, danrosen25 commented
Bring into 8.7.0 after the ESMX Fix

2024-09-05 14:56 UTC, merged